### ISSUE TITLE
Possible to pick a single color from a palette?

### ISSUE THREAD

**Issue by ColdCapital** [wanglongqi/ColorBrewer#1]
wanglongqi-
I just discovered this package... Awesome!
Is it possible to pick a single color from a palette? For example, instead of pulling all of the colors defined by:

` GetPalette[Set1, 4]`

Can I select only the "second" color from this palette, ie "blue"?
Thanks again,
Paul

**Comment by alphamodel** [comment]
`Palette` is just a list of colors, feel free to index through it.

**Comment by ColdCapital** [comment]
Of course! Thanks so much...
